
INSERT INTO TRAINEE (ID, FIRSTNAME, FAMILYNAME) VALUES(1, 'John', 'Doe') 

INSERT INTO TRAINEE (ID, FIRSTNAME, FAMILYNAME) VALUES(2, 'Jane', 'Doe') 

INSERT INTO TRAINEE (ID, FIRSTNAME, FAMILYNAME) VALUES(3, 'Jim', 'Taylor') 

INSERT INTO SUBJECT (SUBJECT_ID, NAME, SCORE) VALUES(1,'Java',3)

INSERT INTO SUBJECT (SUBJECT_ID, NAME, SCORE) VALUES(2,'SQL',2)

INSERT INTO SUBJECT (SUBJECT_ID, NAME, SCORE) VALUES(3,'PHP',4)